name: 'Clean Action'
description: 'Clean the workspace after all steps are done'
inputs:
  workspace:
    description: >
      The path to the workspace that we will clean up after everything is done
    default: ${{ github.workspace }}
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
